#!/usr/bin/env python

import sys, json, math;

f = open(sys.argv[1], 'r');

assert(f.readline() == '# nav-recorder v1\n');
assert(f.readline() == '# device=Google Pixel 6 Pro android=16 sdk=36\n');

data = dict();
for line in f:
    if line[0] == '#': continue;
    arr = line[:-1].split(','); # strip \n
    if arr[0] not in data: data[arr[0]] = list();
    arr[1] = int(arr[1]);
    arr[2] = int(arr[2]);
    arr[3:] = [float(n) if n != '' else None for n in arr[3:]];
    data[arr[0]].append(arr[1:]);

def findmax(sensor):
    m = max(data[sensor][0][2:]);
    for measurement in data[sensor]:
        m = max(max(measurement[2:]), m);
    return m

def dumpmaxes():
    print('max acc: {}'.format(findmax('acc')));
    print('max gyr: {}'.format(findmax('gyr')));
    print('max lac: {}'.format(findmax('lac')));

def findmaxdiff(sensor):
    m = max([abs(b - a) for a,b in zip(data[sensor][0][2:], data[sensor][1][2:])]);
    for i in range(2, len(data[sensor])):
        m = max(max([abs(b - a) for a,b in zip(data[sensor][i-1][2:], data[sensor][i][2:])]), m);
    return m

def dumpmaxdiffs():
    print('max diff acc: {}'.format(findmaxdiff('acc')));
    print('max diff gyr: {}'.format(findmaxdiff('gyr')));
    print('max diff lac: {}'.format(findmaxdiff('lac')));

# first, second := [time_sec, [vec]]
def trapezoid(first, second):
    return [0.5 * (first[1][i] + second[1][i]) * (second[0] - first[0]) for i in range(3)]

def do_integrate(grav):
    # [time, [lac], [v], [x]]
    limit = len(data['acc']);
    output = list();
    time_start = data['acc'][0][0] / 1e9;
    output.append([0, [data['acc'][0][2:][j] - grav[j] for j in range(3)], [0,0,0], [0,0,0]]);
    for i in range(1, limit):
        time = data['acc'][i][0] / 1e9 - time_start;
        lac = [data['acc'][i][2:][j] - grav[j] for j in range(3)];
        delta_v = trapezoid([output[i-1][0], output[i-1][1]], [time, lac]);
        v = [output[i-1][2][j] + delta_v[j] for j in range(3)];
        delta_x = trapezoid([output[i-1][0], output[i-1][2]], [time, v]);
        x = [output[i-1][3][j] + delta_x[j] for j in range(3)];
        output.append([time, lac, v, x]);
    return output;

def lac_stats():
    return stats(data['lac'], 2);
def stats(data_, offset, limit):
    mean = [sum(data_[i][offset + j] for i in range(limit)) / limit for j in range(3)]
    sum_squared_residuals = [sum((data_[i][offset + j] - mean[j]) ** 2 for i in range(limit)) for j in range(3)]
    sigma = [math.sqrt(sum_squared_residuals[i] / (limit - 1)) for i in range(3)]
    #print("mean: {}".format(mean));
    #print("sigma: {}".format(sigma));
    return mean;

# TODO: test for consistency of reporting interval to see if should weight the average by the dt's
# also need to assign timestamps
def denoise(sensor, ratio):
    output = list();
    for i in range(math.ceil(len(data[sensor]) / ratio)):
        values = [a[2:] for a in data[sensor][i*ratio:(i+1)*ratio]];
        mean = [sum(values[i][j] for i in range(len(values))) / len(values) for j in range(3)];
        output.append(mean);
    return output;

def findmax_2(vectors):
    m = max(vectors[0]);
    for vec in vectors:
        m = max(max(vec), m);
    return m;
def findmaxdiff_2(vectors):
    m = max([abs(b - a) for a,b in zip(vectors[0], vectors[1])]);
    for i in range(2, len(vectors)):
        m = max(max([abs(b - a) for a,b in zip(vectors[i-1], vectors[i])]), m);
    return m;

#clean = denoise('acc', 45);
#print("max acc: {}".format(findmax_2(clean)));
#print("max diff acc: {}".format(findmaxdiff_2(clean)));
#print("for lac:");
#lac = stats(data['lac'], 2, 75*19);
#print("for acc:");
acc = stats(data['acc'], 2, 450*19);
#print("for acc{45}:");
#stats(denoise('acc', 45), 0);
# the docs state acc = grav + lac -> grav = acc - lac
#grav = [acc[i] - lac[i] for i in range(3)];
#print("implied gravity is: {}\nwith magnitude: {}".format(grav, math.sqrt(sum(grav[i]**2 for i in range(3)))));
print(json.dumps(do_integrate(acc)));
