#!/usr/bin/env python

import sys, json, math;
import numpy as np;

# FUNCTIONS -----------------------------------------------------------------------------------

def findmax(sensor):
    m = max(data[sensor][0][2:]);
    for measurement in data[sensor]:
        m = max(max(measurement[2:]), m);
    return m

def findmatch():
    # accelerometer seems to start first in the data I have
    first_gyr = data['gyr'][0][0];
    i = 0;
    while data['acc'][i][0] != first_gyr and i < 6: i += 1;
    if i == 6: raise Exception('no match to first gyro point within first 6 accelerometer points');
    return i;

# first, second := [time_sec, [vec]]
def trapezoid(first, second):
    return [0.5 * (first[1][i] + second[1][i]) * (second[0] - first[0]) for i in range(3)]

def stats(data_, offset, limit):
    mean = [sum(data_[i][offset + j] for i in range(limit)) / limit for j in range(3)]
    sum_squared_residuals = [sum((data_[i][offset + j] - mean[j]) ** 2 for i in range(limit)) for j in range(3)]
    sigma = [math.sqrt(sum_squared_residuals[i] / (limit - 1)) for i in range(3)]
    return (mean, sigma);

def omega(gyr):
    return math.sqrt(sum(axis**2 for axis in gyr));

def do_gyr_integrate():
    # [time, omega, [gyr], [rotmat]]
    # rotmat rotates a vector in that timepoint's device coordinates into the initial timepoint's device coordinates
    limit = min(len(data['acc']), len(data['gyr']));
    output = list();
    time_start = data['gyr'][0][0] / 1e9;
    output.append([0, omega(data['gyr'][0][2:]), data['gyr'][0][2:], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]]);
    for i in range(1, limit):
        cur = [data['gyr'][i][0] / 1e9 - time_start, data['gyr'][i][2:]];
        prev = [data['gyr'][i - 1][0] / 1e9 - time_start, data['gyr'][i - 1][2:]];
        rot_vec = trapezoid(prev, cur);
        theta = omega(rot_vec);
        if theta == 0:
            print('!!! DIVIDE BY ZERO !!!', file=sys.stderr);
            print('i = {}'.format(i), file=sys.stderr);
            print('cur = {}'.format(cur), file=sys.stderr);
            print('prev = {}'.format(prev), file=sys.stderr);
            print('rot_vec = {}'.format(rot_vec), file=sys.stderr);
            rot_cur_to_prev = np.eye(3);
        else:
            axis = [a / theta for a in rot_vec];
            cos_ = math.cos(theta);
            cos_2 = 1 - cos_;
            sin_ = math.sin(theta);
            rot_cur_to_prev = np.array([[cos_2 * axis[0]**2 + cos_, cos_2 * axis[0] * axis[1] - sin_ * axis[2], cos_2 * axis[0] * axis[2] + sin_ * axis[1]],
                      [cos_2 * axis[1] * axis[0] + sin_ * axis[2], cos_2 * axis[1]**2 + cos_, cos_2 * axis[1] * axis[2] - sin_ * axis[0]],
                      [cos_2 * axis[2] * axis[0] - sin_ * axis[1], cos_2 * axis[2] * axis[1] + sin_ * axis[0], cos_2 * axis[2]**2 + cos_]]);
        rot_prev_to_orig = np.array(output[i - 1][3]);
        rot_cur_to_orig = np.matmul(rot_prev_to_orig, rot_cur_to_prev).tolist();
        # putting in omega for consistency with previous right-rule outputs. I don't think it really matters/is useful;
        # I don't think I've looked at it at all.
        output.append([cur[0], omega(data['gyr'][i][2:]), data['gyr'][i][2:], rot_cur_to_orig]);
    return output;

def do_coordinate_transform(gyr_solution):
    output = list();
    for i in range(0, len(gyr_solution)):
        if (diff := data['acc'][i][0] - data['gyr'][i][0]) != 0:
            if not (i == 347474 and diff == -8605):
                raise Exception("on i = {} diff is {} acc timestamp {} != gyr timestamp {}".format(i, diff, data['acc'][i][0], data['gyr'][i][0]));
        acc_orig = np.matmul(np.array(gyr_solution[i][3]), np.array(data['acc'][i][2:])).tolist();
        output.append(acc_orig);
    return output;

def do_final_integrate(gyr_solution, acc_origs, grav):
    # [time, omega, [omega], [rotmat], [lac], [v], [x]]
    limit = min(len(data['acc']), len(data['gyr']));
    output = list();
    time_start = data['acc'][0][0] / 1e9;
    output.append([gyr_solution[0][0], gyr_solution[0][1], gyr_solution[0][2], gyr_solution[0][3], [acc_origs[0][j] - grav[j] for j in range(3)], [0,0,0], [0,0,0]]);
    for i in range(1, limit):
        time = data['acc'][i][0] / 1e9 - time_start;
        lac = [acc_origs[i][j] - grav[j] for j in range(3)];
        delta_v = trapezoid([output[i - 1][0], output[i - 1][4]], [time, lac]);
        v = [output[i - 1][5][j] + delta_v[j] for j in range(3)];
        delta_x = trapezoid([output[i - 1][0], output[i - 1][5]], [time, v]);
        x = [output[i - 1][6][j] + delta_x[j] for j in range(3)];
        output.append([gyr_solution[i][0], gyr_solution[i][1], gyr_solution[i][2], gyr_solution[i][3], lac, v, x]);
    return output;

def rotmat_to_axis_angle(R):
    theta = math.acos((sum(R[i][i] for i in range(3)) - 1) / 2)
    omega = [R[2][1] - R[1][2], R[0][2] - R[2][0], R[1][0] - R[0][1]];
    factor = 1 / (2 * math.sin(theta))
    omega = [factor * omega[i] for i in range(3)]
    return (theta, omega)
def rnd(x):
    return (round(x[0], 3), [round(x[1][i], 6) for i in range(3)])

def dump_stats(mean, sigma):
    print("mean: {}".format([round(a, 6) for a in mean]), file=sys.stderr);
    print("sigma: {}".format([round(a, 6) for a in sigma]), file=sys.stderr);
    t = [round(mean[i] / sigma[i], 6) for i in range(3)];
    print("t: {}".format(t), file=sys.stderr);

# KALMAN -----------------------------------------------------------------------------------------

# lac := [lac]
def do_kalman_1d(lac, calib_n):
    sigma2_a = sum(a**2 for a in lac) / len(lac);
    sigma2_z = sum(lac[i]**2 for i in range(calib_n)) / calib_n;
    print("sigma2_a = {:.6f}\nsigma2_z = {:.6f}".format(sigma2_a, sigma2_z), file=sys.stderr);
    F = 0;
    G = 1;
    Q = sigma2_a;
    H = 1;
    R = sigma2_z;
    xhat = [None for i in range(len(lac))];
    P = [None for i in range(len(lac))];
    xhat[0] = 0;
    P[0] = 0;
    K = [None for i in range(len(lac))];
    for k in range(1, len(lac)):
        xhat_prior = F * xhat[k - 1];
        P_prior = F * P[k - 1] * F + Q;
        ytilde = lac[k] - H * xhat_prior;
        S = H * P_prior * H + R;
        K[k] = P_prior * H * (1 / S);
        xhat[k] = xhat_prior + K[k] * ytilde;
        P[k] = (1 - K[k] * H) * P_prior;
    return [xhat, P, K];

# lac := [time, lac]
def do_1d_integrate(lac):
    output = list();
    output.append([lac[0][0], lac[0][1], 0, 0]);
    for i in range(1, len(lac)):
        delta_v = 0.5 * (lac[i][1] + lac[i - 1][1]) * (lac[i][0] - lac[i - 1][0]);
        v = output[i - 1][2] + delta_v;
        delta_x = 0.5 * (v + output[i - 1][2]) * (lac[i][0] - lac[i - 1][0]);
        x = output[i - 1][3] + delta_x;
        output.append([lac[i][0], lac[i][1], v, x]);
    return output;

# MAIN -------------------------------------------------------------------------------------------

f = open(sys.argv[1], 'r');

assert(f.readline() == '# nav-recorder v1\n');
#assert(f.readline() == '# device=Google Pixel 6 Pro android=16 sdk=36\n');

data = dict();
for line in f:
    if line[0] == '#': continue;
    arr = line[:-1].split(','); # strip \n
    if arr[0] not in data: data[arr[0]] = list();
    arr[1] = int(arr[1]);
    arr[2] = int(arr[2]);
    arr[3:] = [float(n) if n != '' else None for n in arr[3:]];
    data[arr[0]].append(arr[1:]);

ACC_MAX = 156;
GYR_MAX = 34;
acc_max = findmax('acc');
gyr_max = findmax('gyr');
if acc_max >= ACC_MAX:
    print("accelerometer clipped (max = {})".format(acc_max), file=sys.stderr);
if gyr_max >= GYR_MAX:
    print("gyro clipped (max = {})".format(gyr_max), file=sys.stderr);

data['acc'] = data['acc'][findmatch():];
assert(data['acc'][0][0] - data['gyr'][0][0] == 0);
print('difference in number of points is {}'.format(len(data['acc']) - len(data['gyr'])), file=sys.stderr);

gyr_solution = do_gyr_integrate();
acc_origs = do_coordinate_transform(gyr_solution);

calib_n = int(450 * float(sys.argv[2]));
mean, sigma = stats(acc_origs, 0, calib_n);
print('acc_origs:', file=sys.stderr);
dump_stats(mean, sigma);
grav_mag = omega(mean);
print("magnitude {:.4f} at angle {:.3f} rad / {:.1f} deg".format(grav_mag, math.acos(mean[2] / grav_mag), math.acos(mean[2] / grav_mag) * 180 / math.pi), file=sys.stderr);

lac = [acc_origs[i][1] - mean[1] for i in range(len(acc_origs))];
lac_with_times = [[gyr_solution[i][0], lac[i]] for i in range(len(lac))];
kalman = do_kalman_1d(lac, calib_n);
base_integrate = do_1d_integrate(lac_with_times);
kalman_integrate = do_1d_integrate([[gyr_solution[i][0], kalman[0][i]] for i in range(len(kalman[0]))]);
print(json.dumps({'kalman': kalman, 'base_integrate': base_integrate, 'kalman_integrate': kalman_integrate}));
print("final point of base integration:   {}".format(base_integrate[-1]), file=sys.stderr);
print("final point of kalman integration: {}".format(kalman_integrate[-1]), file=sys.stderr);

#solution = do_final_integrate(gyr_solution, acc_origs, mean);
#print(json.dumps(solution));
#print("rotation at final point ({}): {}".format(len(solution) - 1, rnd(rotmat_to_axis_angle(solution[-1][3]))), file=sys.stderr);
#print("final point: {}".format(solution[-1]), file=sys.stderr);
#
#
#lac_mean, lac_sigma = stats([a[4] for a in solution], 0, len(solution));
#print('for lac over the entire file:', file=sys.stderr);
#dump_stats(lac_mean, lac_sigma);


## calibrating without gyro transform
#mean, sigma = stats(data['acc'], 2, calib_n)
#dump_stats(mean, sigma);
#
#solution, acc_origs = do_combined_integrate(mean);
#
#ao_mean, ao_sigma = stats(acc_origs, 0, calib_n);
#print('for acc_origs', file=sys.stderr);
#dump_stats(ao_mean, ao_sigma);
#
#
#ao_ao_mean, ao_ao_sigma = stats([[acc_origs[i][j] - ao_mean[j] for j in range(3)] for i in range(len(acc_origs))], 0, calib_n);
#print('for acc_orig - mean(acc_orig)', file=sys.stderr);
#dump_stats(ao_ao_mean, ao_ao_sigma);

#gyr_integrate = do_gyr_integrate();
#print(json.dumps(gyr_integrate));
#print("rotation at point 1000: {}".format(rnd(rotmat_to_axis_angle(gyr_integrate[1000][3]))), file=sys.stderr);









# UNUSED CODE --------------------------------------------------------------------
def dumpmaxes():
    print('max acc: {}'.format(findmax('acc')));
    print('max gyr: {}'.format(findmax('gyr')));
    print('max lac: {}'.format(findmax('lac')));

def findmaxdiff(sensor):
    m = max([abs(b - a) for a,b in zip(data[sensor][0][2:], data[sensor][1][2:])]);
    for i in range(2, len(data[sensor])):
        m = max(max([abs(b - a) for a,b in zip(data[sensor][i-1][2:], data[sensor][i][2:])]), m);
    return m

def dumpmaxdiffs():
    print('max diff acc: {}'.format(findmaxdiff('acc')));
    print('max diff gyr: {}'.format(findmaxdiff('gyr')));
    print('max diff lac: {}'.format(findmaxdiff('lac')));

def lac_stats():
    return stats(data['lac'], 2);

# TODO: test for consistency of reporting interval to see if should weight the average by the dt's
# also need to assign timestamps
def denoise(sensor, ratio):
    output = list();
    for i in range(math.ceil(len(data[sensor]) / ratio)):
        values = [a[2:] for a in data[sensor][i*ratio:(i+1)*ratio]];
        mean = [sum(values[i][j] for i in range(len(values))) / len(values) for j in range(3)];
        output.append(mean);
    return output;

def findmax_2(vectors):
    m = max(vectors[0]);
    for vec in vectors:
        m = max(max(vec), m);
    return m;
def findmaxdiff_2(vectors):
    m = max([abs(b - a) for a,b in zip(vectors[0], vectors[1])]);
    for i in range(2, len(vectors)):
        m = max(max([abs(b - a) for a,b in zip(vectors[i-1], vectors[i])]), m);
    return m;
def do_integrate(grav):
    # [time, [lac], [v], [x]]
    limit = len(data['acc']);
    output = list();
    time_start = data['acc'][0][0] / 1e9;
    output.append([0, [data['acc'][0][2:][j] - grav[j] for j in range(3)], [0,0,0], [0,0,0]]);
    for i in range(1, limit):
        time = data['acc'][i][0] / 1e9 - time_start;
        lac = [data['acc'][i][2:][j] - grav[j] for j in range(3)];
        delta_v = trapezoid([output[i-1][0], output[i-1][1]], [time, lac]);
        v = [output[i-1][2][j] + delta_v[j] for j in range(3)];
        delta_x = trapezoid([output[i-1][0], output[i-1][2]], [time, v]);
        x = [output[i-1][3][j] + delta_x[j] for j in range(3)];
        output.append([time, lac, v, x]);
    return output;
def do_combined_integrate(grav):
    limit = min(len(data['acc']), len(data['gyr']));
    output = list();
    time_start = data['acc'][0][0] / 1e9;
    dbg_out = list();
    # findmatch() guarantees the first points have matching timestamps
    output.append([0, omega(data['gyr'][0][2:]), data['gyr'][0][2:], [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                   [data['acc'][0][2:][j] - grav[j] for j in range(3)], [0,0,0], [0,0,0]]);
    dbg_out.append(data['acc'][0][2:]);
    for i in range(1, limit):
        if (diff := data['acc'][i][0] - data['gyr'][i][0]) != 0:
            raise Exception("on i = {} diff is {} acc timestamp {} != gyr timestamp {}".format(i, diff, data['acc'][i][0], data['gyr'][i][0]));
        cur = [data['gyr'][i][0] / 1e9 - time_start, data['gyr'][i][2:]];
        prev = [data['gyr'][i - 1][0] / 1e9 - time_start, data['gyr'][i - 1][2:]];
        rot_vec = trapezoid(prev, cur);
        theta = omega(rot_vec);
        if theta == 0:
            print('!!! DIVIDE BY ZERO !!!', file=sys.stderr);
            print('i = {}'.format(i), file=sys.stderr);
            print('cur = {}'.format(cur), file=sys.stderr);
            print('prev = {}'.format(prev), file=sys.stderr);
            print('rot_vec = {}'.format(rot_vec), file=sys.stderr);
            rot_cur_to_prev = np.eye(3);
        else:
            axis = [a / theta for a in rot_vec];
            cos_ = math.cos(theta);
            cos_2 = 1 - cos_;
            sin_ = math.sin(theta);
            rot_cur_to_prev = np.array([[cos_2 * axis[0]**2 + cos_, cos_2 * axis[0] * axis[1] - sin_ * axis[2], cos_2 * axis[0] * axis[2] + sin_ * axis[1]],
                      [cos_2 * axis[1] * axis[0] + sin_ * axis[2], cos_2 * axis[1]**2 + cos_, cos_2 * axis[1] * axis[2] - sin_ * axis[0]],
                      [cos_2 * axis[2] * axis[0] - sin_ * axis[1], cos_2 * axis[2] * axis[1] + sin_ * axis[0], cos_2 * axis[2]**2 + cos_]]);
        rot_prev_to_orig = np.array(output[i - 1][3]);
        rot_cur_to_orig = np.matmul(rot_prev_to_orig, rot_cur_to_prev);
        acc_orig = np.matmul(rot_cur_to_orig, np.array(data['acc'][i][2:])).tolist();
        dbg_out.append(acc_orig);
        lac = [acc_orig[j] - grav[j] for j in range(3)];
        delta_v = trapezoid([output[i - 1][0], output[i - 1][4]], [cur[0], lac]);
        v = [output[i - 1][5][j] + delta_v[j] for j in range(3)];
        delta_x = trapezoid([output[i - 1][0], output[i - 1][5]], [cur[0], v]);
        x = [output[i - 1][6][j] + delta_x[j] for j in range(3)];
        output.append([cur[0], omega(data['gyr'][i][2:]), data['gyr'][i][2:], rot_cur_to_orig.tolist(), lac, v, x]);
    return (output, dbg_out);


#clean = denoise('acc', 45);
#print("max acc: {}".format(findmax('acc')));
#print("max diff acc: {}".format(findmaxdiff('acc')));
#print("max acc(45): {}".format(findmax_2(clean)));
#print("max diff acc(45): {}".format(findmaxdiff_2(clean)));
#print("for acc:");
#acc = stats(data['acc'], 2, 450*10);
#print("for acc{45}:");
#stats(clean, 0, 10*10);

# the docs state acc = grav + lac -> grav = acc - lac
#grav = [acc[i] - lac[i] for i in range(3)];
#print("implied gravity is: {}\nwith magnitude: {}".format(grav, math.sqrt(sum(grav[i]**2 for i in range(3)))));
#print(json.dumps(do_integrate(acc)));
